# Generated by Django 5.2.11 on 2026-02-04 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='raceresult',
            new_name='race_racere_created_b0c96d_idx',
            old_name='race_raceres_created_2a4a23_idx',
        ),
    ]
